### ISSUE TITLE
URL is down?

### ISSUE THREAD

**Issue by franklapoint** [ParkinT/bible-bot#3]
https://disciplr.herokuapp.com/bible is not available.  Did it get moved or taken down?

**Comment by ParkinT** [comment]
Thanks for the notification.  I am not sure what happened there; time for some troubleshooting.

**Comment by ParkinT** [comment]
This problem "fixed itself".
By mere coincidence, in my **day job** we had an issue with a Redis server and while I was searching the web for some ideas on the problem I read numerous posts and comments about a recent widespread hacking effort. Apparently someone (or group) was applying password authentication to Redis datastores that did not have any.  This rendered them inoperable because the services calling on them were not providing any authentication credentials!
I strongly suspect that was what struck this application.  In all these cases once the Redis instance was rebooted - and read its internal `.conf` file which had NOT AUTH set - all was back to normal.
Thanks @franklapoint for pointing this out.  It is gratifying to learn others are making use of this.

**Comment by franklapoint** [comment]
Glad you were able to work it out and fairly easy to resolve.  I  will have to look into some of the configuration of our Redis datastores, that our team are using, as well.  Nice catch.
